services:
  pedidos:
    container_name: pedidos-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT:-3004}:${PORT:-3004}"
    environment:
      NODE_ENV: production
      PORT: ${PORT:-3004}
    restart: unless-stopped
